// flow-typed signature: 63398925833bc24f9700da9e355e72e4
// flow-typed version: <<STUB>>/postcss-color-function_v^4.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-color-function'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-color-function' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-color-function/index' {
  declare module.exports: $Exports<'postcss-color-function'>;
}
declare module 'postcss-color-function/index.js' {
  declare module.exports: $Exports<'postcss-color-function'>;
}
